name: sync-submodules
on: [push]
jobs:
  sync-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@main

      - name: Run the script
        run: node .

      - name: Sync submodules
        run: git submodule update --recursive --remote
      
      - name: Print changes
        run: git status
