name: sync-submodules
on: [push]
jobs:
  sync-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@main
      - name: Print discovered submodules using approach 1
        run: test .gitmodules && git config --file .gitmodules --name-only --get-regexp path
      - name: Print discovered submodules using approach 2
        run: git submodule status
      - name: Sync submodules
        run: git submodule update --recursive --remote
      - name: Print changes
        run: git status
