name: sync-submodules
on: [push]
jobs:
  sync-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@main
      
      # TODO: Figure out why this runs and exits with code 1 despite `test`
      # - name: Print discovered submodules using approach 1
      #   run: test -f .gitmodules && git config --file .gitmodules --name-only --get-regexp path
      
      - name: Print discovered submodules using approach 2
        run: git submodule status
      
      - name: Sync submodules
        run: git submodule update --recursive --remote
      
      - name: Print changes
        run: git status
