name: sync-submodules
on: [push]
jobs:
  sync-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@main
        with:
          submodules: true
      
      - name: Run `test -f .gitmodules`
        run: test -f .gitmodules && echo ".gitmodules exists" || echo ".gitmodules does not exist"

      - name: Run `git config --file .gitmodules --name-only --list`
        run: test -f .gitmodules && git config --file .gitmodules --name-only --list || echo ".gitmodules does not exist"
      
      - name: Run `git submodule status`
        run: git submodule status
      
      - name: Run `test -d .git/modules`
        run: test -d .git/modules && echo ".git/modules exists" || echo ".git/modules does not exist"

      - name: Run `ls .git/modules`
        run: test -d .git/modules && ls .git/modules || echo ".git/modules does not exist"

      - name: Run `git config --name-only --list | grep "^submodule\..*\.url$"`
        run: git config --name-only --list | grep "^submodule\..*\.url$" | cut -c 11- | rev | cut -c 5- | rev

      - name: Sync submodules
        run: git submodule update --recursive --remote
      
      - name: Print changes
        run: git status
